arch: linear
aug: true
augmentation: RandomCrop
batch_size: 1024
ckpt: ''
ckpt_iter: -1
config_file: null
data: cifar
dist: dp
dist_address: 127.0.0.1:1234
encode_layer: h
encoder_ckpt: ''
eval_freq: 1000
finetune: false
iters: 80000
log_freq: 100
lr: 0.1
lr_schedule: linear
model_id: -1
n_augs_test: 50
n_augs_train: 10
name: ''
node_rank: 0
opt: sgd
precompute_emb_bs: -1
problem: eval
root: ''
save_freq: 100000000
scale_lower: 0.08
seed: -1
status: fail
test_bs: 1024
tmp: false
warmup: 0.0
weight_decay: 0.0001
workers: 2
world_size: 1

time: '2020-07-18T00:55:23'
id: 3549