arch: ResNet50
aug: true
batch_size: 1024
ckpt: ''
color_dist_s: 0.5
config_file: null
data: cifar
dist: ddp
dist_address: '127.0.0.1:1234'
eval_freq: 4800
iters: 48000
log_freq: 48
lr: 4.0
lr_schedule: warmup-anneal
multiplier: 2
name: 'reproduce-cifar10'
node_rank: 0
opt: lars
problem: sim-clr
root: 'none'
save_freq: 4800
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.5
tmp: false
verbose: true
warmup: 0.01
weight_decay: 1.0e-06
workers: 2
world_size: 1