arch: ResNet50
aug: true
batch_size: 2048
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: ddp
dist_address: ''
eval_freq: 12510
gpu: 0
iters: 125100
log_freq: 100
lr: 2.4
lr_schedule: warmup-anneal
momentum: 0.9
multiplier: 2
name: imagenet-reproduce
node_rank: 0
number_of_processes: 16
opt: lars
problem: sim-clr
root: ''
save_freq: 12510
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 4